[mypy]
python_version = 3.12
strict = True
plugins = pydantic.mypy

[mypy-celery.*]
ignore_missing_imports = True

[mypy-weasyprint.*]
ignore_missing_imports = True

[mypy-firebase_admin.*]
ignore_missing_imports = True
